name: app_fisica
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  collection: ^1.19.1
  equatable: ^2.0.7
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  get: ^4.7.2
  go_router: ^15.2.0
  google_sign_in: ^6.3.0
  image: ^4.5.4
  json_annotation: ^4.9.0
  supabase_flutter: ^2.9.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
